name: Unity CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/*.cs') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Setup Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2023.3.0f1

      - name: Run Unit Tests
        uses: game-ci/unity-test-runner@v2
        with:
          unityVersion: 2023.3.0f1

      - name: Build for Windows
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: StandaloneWindows64

      - name: Upload Windows Build
        uses: actions/upload-artifact@v3
        with:
          name: Build-Windows
          path: build/StandaloneWindows64
